spring:
  application:
    name: ud-student-service
  datasource:
    url: jdbc:mysql://localhost:3306/ud-eleap_db?serverTimeZone=America/Lima
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    #hibernate:
    #  ddl-auto: create

server:
  port: 7001

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    status-page-url-path: /swagger-ui.html
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka